language: cpp
matrix:
  include:
  - os: linux
    name: Linux Release
    sudo: required
    before_script:
      - mkdir build
      - cd build
      - cmake ..
    script:
      - cmake --build .

  - os: osx
    name: Mac Release
    before_script:
      - mkdir build
      - cd build
      - cmake ..
    script:
      - cmake --build .

  - os: windows
    name: Windows Release
    before_script:
      - mkdir build
      - cd build
      - cmake ..
    script:
      - cmake --build .
