sudo: required
dist: trusty

language: cpp

compiler:
  - gcc
  - g++
  - clang
  - osx
  - linux

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .

after_script:
  - cmake --build . --target test
