language: cpp
matrix:
  include:
    - os: linux
      name: Linux Release
      sudo: required
      script: scripts/build_linux_travis.sh
#    - os: osx
#      name: Mac Release
#      script: scripts/build_mac_travis.sh
#    - os: windows
#      name: Windows Release
#      install: 7zip
#      script: scripts/build_windows_travis.sh
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: AAAAB3NzaC1yc2EAAAADAQABAAACAQDKyQJY/etlFFwbNicobkMWFk2yA1YkqXD8gh4Q7xd8jqW/yfNDtyKh47qS5XQKaNfEyUJVp7uMMgDDNWvLds9tLiEHGEqd1JC1f9IWXVc65qwIOjcS2cCj3eN2ztdAdorTD1HIhXZDFcVedqqqVYSDl6w0CAE5
  file_glob: true
  file: release/*
  on:
    repo: mitchute/gfunction
    tags: true