language: cpp
matrix:
  include:
    - os: linux
      name: Linux Release
      sudo: required
      script: scripts/build_linux_travis.sh
#    - os: osx
#      name: Mac Release
#      script: scripts/build_mac_travis.sh
#    - os: windows
#      name: Windows Release
#      install: 7zip
#      script: scripts/build_windows_travis.sh
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: nOMvmj1loJBPVYLZEVFfJej1NWHFgW2hzSE/G/Jysp5FGol2RtWXttmZbAfUrczsYDG4Jm5W7YiNVkeE8CzvxiEq6FQSe+OM1+1Zhji5eUXIvPwdh4jMN2x1BmAakqsj4RNRYUH20DH49TSUn0uaFt6OudLXUExbwDzG1izyG7UOKlc6tgJyG45giyQ0wxEhOuBmwOQXC6FzN+Lc+Qo4FLy1NxRjbRpiB9Frfwz/yjhr0WSSPld3uRNl9K5kiG2+on0eiSZiUgKUin+QALZGrH6jTosxgFw+cHzEC3/FYtdEGea2jMQq6OYeVFv8vNYvgQ/KoYziqW7Db8O4akJUXSYX3EnIXa4cUr66gRbWT44cpA8yQSv8SN8cMrzZMMKLP4C6eqrwRMcdRTfvG3Xe+aOfovLte9Q3sj6gWcg0LFofJoOtui8kUOoLWJN5GfAXXKR4vjjDtFmzha4weDt+Yl8mb0GLd6XvU4PEhcL5q/fg8NgyBK0sMTcCSqDSt0c3zptJlOisofb0E2MqVnbSFVhXyhgy02oVEWdh8qOUDWTJ2sYA6DLYb9vPEPerZUl1hzfCHR4CzIENN25unuLGikJxnfA5Pr+4SmIzfYCl6vITQzZbYgK3UdC+h0a6AhNckmboNMB5Ns3DvG1+3Si3T/tGZtopUrslgj4bQFPgKyY=
  file: release/*
  on:
    repo: mitchute/gfunction
    tags: true